### PR TITLE
Use encoding from original Android compile task

### LINKED ISSUE #103: String with non-ASCII characters broken
It seems Retrolambda messes up string encoding. This string literal:

`Simon Péter`

becomes this:

`Simon PĂ©ter`

I tried to decompile the code in both `build/retrolambda` and `build/intermediates/classes` with [jd-gui](http://jd.benow.ca/). (I tried `javap`, too, but it always printed the correct string :S `javap -c -constants -v -l MainActivity.class > log.txt`).

For me it seems the bytecode contains the correct string if i turn off Retrolambda totally, but it contains the bad string in both places if i turn it on.

Anyway, i created a [simple example project](https://github.com/WonderCsabo/RetroEncoding) which can reproduce the issue. If you comment the retrolambda plugin usage and use java 1.7, it will display the correct string. If you leave it as-is, so retrolambda is used, incorrect strings are displayed.

Of course i am on Windows (8.1). If i add `JAVA_OPTS=-Dfile.encoding=UTF-8`, it works with Retrolambda, too, but it shouldn't be necessary (as the Retrolambda-less config does not need this).

### PR DESCRIPTION
**Pull request by WonderCsabo**
Fixes #103.

### CODE REVIEW

**Comment by WonderCsabo** [comment]
@evant i am wondering, shouldn't we copy all properties of the original task?

**Comment by WonderCsabo** [comment]
@evant can i get some feedback on this one?

**Comment by evant** [comment]
Actually, I think I finally found a better way to change the javaCompile task so that this and many other things aren't required, check out my last commit on the develop branch.

**Comment by WonderCsabo** [comment]
I agree that way is much cleaner and renders may change obsolete. I will
test it this evening. Thanks!

**Comment by WonderCsabo** [comment]
I verified your commit fixed this issue, so i am closing this PR.

**Pull request closed without merging**
