### PR TITLE
Adds support for the Android Feature plugin

### PR DESCRIPTION
**Pull request by athornz**
The feature plugin is a new plugin type used in Instant Apps.

### CODE REVIEW

**Comment by evant** [comment]
Looks good, can we get a test for this?

**Comment by evant** [comment]
Hm, yep I'm getting the same error. Adding
```groovy
compileOptions {
    sourceCompatibility JavaVersion.VERSION_1_8
    targetCompatibility JavaVersion.VERSION_1_8
}
```
seems to cause I new error
```
com.sun.tools.javac.code.Symbol$CompletionFailure: class file for java.lang.invoke.MethodType not found
```
I'm getting that error running trying to run the sample app too.

**Comment by evant** [comment]
Figured it out, apprently features have a feature varaint _and_ a library variant. Adding
```groovy
android.libraryVariants.all { BaseVariant variant ->
    configureCompileJavaTask(project, variant, transform)
}
```
seems to fix it.

**Comment by athornz** [comment]
Did you add the compile options to the test projects? I'm still getting a myriad of errors with both changes 😕

**Comment by evant** [comment]
The remaining tests I see failing don't seem to be related to this change. If this is the case you are seeing, I can merge this and make a sepreate pr for the tests.

**Comment by athornz** [comment]
ah ok I think that may be the case. I'm happy for this to be merged.

**Pull request merged**
